# Generated by Django 3.1.1 on 2020-10-05 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'admin_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinators',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'coordinators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataEntered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('data_entered', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'data_entered',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('roles', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WardDetails',
            fields=[
                ('ward', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('details', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ward_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='bulk_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=50)),
                ('roles', models.CharField(max_length=50)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='coordinat_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('cordname', models.CharField(max_length=50, null=True)),
                ('contnum', models.CharField(max_length=50, null=True)),
                ('altnum', models.CharField(max_length=50, null=True)),
                ('schfrom', models.TimeField()),
                ('schto', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('docname', models.CharField(max_length=50, null=True)),
                ('contnum', models.CharField(max_length=50, null=True)),
                ('altnum', models.CharField(max_length=50, null=True)),
                ('schfrom', models.TimeField()),
                ('schto', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='formupdate',
            fields=[
                ('date', models.CharField(max_length=50, null=True)),
                ('tme', models.CharField(max_length=50, null=True)),
                ('upby', models.CharField(max_length=50, null=True)),
                ('contnum', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('wardnum', models.CharField(max_length=50, null=True)),
                ('wardtype', models.CharField(max_length=50, null=True)),
                ('vacbed', models.CharField(max_length=50, null=True)),
                ('ventbed', models.CharField(max_length=50, null=True)),
                ('oxybed', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
